apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: test
  namespace: argocd
spec: 
  destination: 
    namespace: test
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    path: apps/test
    repoURL: "https://github.com/solas98/cicdtest"
    targetRevision: main
  syncPolicy:
    automated:
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true